[package]
name = "hypothetical-bvdf-crate"
publish = false
version = "1.2.3"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
indexmap = "1.9.3"
thiserror = "1.0.40"
tracing = "0.1.37"

[dev-dependencies]
steamlocate = { path = "../.." }
