[package]
name = "steamlocate"
version = "1.1.1"
authors = ["William Venner <william@venner.io>"]
edition = "2018"
repository = "https://github.com/WilliamVenner/steamlocate-rs"
license = "MIT"
description = "Rust Crate for locating Steam game installation directories (and Steam itself!)"
readme = "README.md"
keywords = ["steam", "vdf", "appmanifest", "directory", "steamapps"]
categories = ["os", "hardware-support", "filesystem", "accessibility"]

[features]
default = []
shortcuts_extras = ["dep:crc", "dep:indexmap", "dep:thiserror"]
steamid_ng = ["dep:steamid-ng"]

[dependencies]
crc = { version = "3.0", optional = true }
indexmap = { version = "1.9", optional = true }
keyvalues-parser = "0.1"
steamid-ng = { version = "1", optional = true }
steamy-vdf = "0.2"
thiserror = { version = "1", optional = true }

[target.'cfg(target_os="windows")'.dependencies]
winreg = "0.10"
[target.'cfg(not(target_os="windows"))'.dependencies]
dirs = "3"

[dev-dependencies]
bstr = "1.4.0"
